spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=driversandcarsliqui"
    username: driversandcarsuser
    password: 123
  liquibase:
    user: driversandcarsuser
    password: 123
    change-log: 'classpath:db-migrations/changelog.xml'
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
server:
  port: 42100
internal:
  api:
    predicate-uuid: ${PREDICATE_UUID:"public.uuid_generate_v4()"}