spring:
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:54320}/${DATABASE_NAME:postgres}?currentSchema=${DATABASE_SCHEMA:public}"
    username: ${DATABASE_USERNAME:driversandcarsuserusage}
    password: ${DATABASE_PASSWORD:123}
  liquibase:
    user: ${LIQUIBASE_USERNAME:driversandcarsuser}
    password: ${LIQUIBASE_PASSWORD:123}
    change-log: 'classpath:db-migrations/changelog.xml'
  jpa:
    show-sql: true
server:
  port: 42100